# Generated by Django 4.1.5 on 2023-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0003_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
