# Generated by Django 4.1.5 on 2023-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0004_conference_views_seminar_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statya',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='statya',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='statya',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
