# Generated by Django 4.1.5 on 2023-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0005_statya_archive_statya_name_en_statya_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='organization_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='organization_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='organization_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
