# Generated by Django 4.1.5 on 2023-02-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0008_author_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmapolls.organization'),
        ),
    ]
