# Generated by Django 4.1.5 on 2023-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0009_alter_conference_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='fio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
