# Generated by Django 4.1.5 on 2023-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0011_subdivision_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='image',
        ),
        migrations.AddField(
            model_name='subdivision',
            name='issn',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
