# Generated by Django 4.1.5 on 2023-02-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0012_remove_subdivision_image_subdivision_issn'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
