# Generated by Django 4.1.5 on 2023-02-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0013_subdivision_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subdivision', to='pharmapolls.organization'),
        ),
    ]
