# Generated by Django 4.1.5 on 2023-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0016_seminar_fio_en_seminar_fio_ru_seminar_fio_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='sponsor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sponsor_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sponsor_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sponsor_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='sponsor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='sponsor_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='sponsor_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='sponsor_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
