# Generated by Django 4.1.5 on 2023-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0017_alter_conference_sponsor_alter_conference_sponsor_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_gallery',
            name='videourl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
