# Generated by Django 4.1.5 on 2023-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0018_alter_video_gallery_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='downloadview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
