# Generated by Django 4.1.5 on 2023-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0023_alter_author_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
