# Generated by Django 4.1.5 on 2023-01-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0035_remove_jurnal_author_en_remove_jurnal_author_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='author',
        ),
    ]
