# Generated by Django 4.1.5 on 2023-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0036_remove_jurnal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='login_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='telegram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
