# Generated by Django 4.1.5 on 2023-02-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0038_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
