# Generated by Django 4.1.5 on 2023-02-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0043_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
