# Generated by Django 4.1.5 on 2023-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0032_banner_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='organization_uz',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='organization_uz',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='organization_uz',
        ),
    ]
