# Generated by Django 4.1.5 on 2023-01-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0034_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='author_uz',
        ),
    ]
