# Generated by Django 4.1.5 on 2023-02-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0040_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmapolls.organization'),
        ),
    ]
