# Generated by Django 4.1.5 on 2023-02-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapolls', '0041_user_organization'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
